# Generated by Django 2.1.5 on 2019-01-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='LiteracyData',
        ),
    ]
