# Generated by Django 2.1.5 on 2019-01-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0002_auto_20190123_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('all', 'All'), ('rural', 'Rural'), ('urban', 'Urban')], max_length=10)),
                ('year', models.SmallIntegerField()),
                ('male', models.SmallIntegerField()),
                ('female', models.SmallIntegerField()),
                ('total', models.SmallIntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapdata.Region')),
            ],
        ),
    ]
